### ISSUE TITLE
"Endless Skip" Bug

### ISSUE THREAD

**Issue by VirusMV** [corentin-c/SpotifyAutoPatcher#35]
(I encountered the following bug in versions 1.1.0 and 1.2.0)
I'm not sure if it's an isolated incident or a recurring and known bug; but after installing the patched Spotify, if I try to skip a song (whether shuffle mode is on or off), it keeps skipping songs until it stops on a random song after 20-30 seconds.

Edit (19th june): Today, after months of using the app, it happened the same bug but on the normal Spotify app too, same bug with same behaviours. I just wanted to report this beacuse at this point I think it's something in Spotify itself and not the patch

**Comment by ruguysgoingtrickortreating** [comment]
having the same issue, but for me i didnt even have to press skip i just tried playing one of the songs on my playlist and this happened

**Comment by ruguysgoingtrickortreating** [comment]
update: my experience, the "not having to press skip for this bug," seems to happen when i play a song from my playlist while shuffle is on. i can play a song with shuffle off just fine, that is until i skip. it breaks again if i skip, even if i try playing a new song in the playlist with shuffle off, and i have to fuck with playing and pausing and toggling shuffle on and off to get it to work again. also, when the song ends, it skips a few songs, ranging from only one song to like 10.

**Comment by corentin-c** [comment]
try to patch with the newest 5.31.2 revanced patches that solves this, SpotifyAutoPatcher will have the latest ones

**Comment by corentin-c** [comment]
5.31.1, fixed the skipping issue, 5.31.2 fixed the login issue but brought back the skipping issue. We need to wait for a new patch...

**Comment by vladesbit** [comment]
same problem, keep skipping the songs, how to fix it?

**Comment by vladesbit** [comment]
do i need log in Spotify app what i download from playstore, before using Autopatcher

**Comment by nbeeeeeeeeee** [comment]
Yiyang highland barley

**Comment by nbeeeeeeeeee** [comment]
I have the same situation waiting to be solved.

**Comment by Deftera186** [comment]
This is blocked until https://github.com/ReVanced/revanced-patches/issues/5451 is resolved. Not related to SpotifyAutoPatcher.

**Comment by luciferianNinja** [comment]
So i still have this problem as well. Has patch#5451 been resolved yet?

**Comment by KapsiF** [comment]
Same issue here on the latest version

**Comment by cclowlowking** [comment]
same issue，its auto stop play when i click any song，hope a new patch ，thanks

**Comment by merazi** [comment]
I'm having the same issue, hope a patch from revanced is published soon.

**Comment by corentin-c** [comment]
Hello everyone, it seems to be fixed, could you please try again ?
